### ISSUE TITLE
fade in effect?

### ISSUE THREAD

**Issue by sanalbakis** [churnlabs/android-ffmpeg-sample#2]
Hi, 
I just wanted to ask, if you know how to use fade-in/out effects in android+ffmpeg? 
I am trying to find a solution since 2 weeks. 
Thanks

**Comment by mikerowehl** [comment]
We've only been using the library for decoding/re-encoding streams, the display stuff we wired up was actually just for testing, we haven't used any of the complex or advanced display functions.
