### ISSUE TITLE
Cannot find -lavformat

### ISSUE THREAD

**Issue by tinchoforever** [churnlabs/android-ffmpeg-sample#5]
billdecaledonia@caledonia /cygdrive/C/Users/billdecaledonia/workspace/FFMpegva/j
ni
$ /cygdrive/c/android-ndk-r6b/ndk-build
Compile thumb  : avjni <= avjni.c
SharedLibrary  : libavjni.so
C:/android-ndk-r6b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/.
./lib/gcc/arm-linux-androideabi/4.4.3/../../../../arm-linux-androideabi/bin/ld.e
xe: cannot find -lavformat
collect2: ld returned 1 exit status
make: **\* [/cygdrive/C/Users/billdecaledonia/workspace/FFMpegva/obj/local/armeab
i/libavjni.so] Error 1

I read that you say that the file is located into the JNI directoy, but it seems that this isn´t working....
Any idea?

**Comment by mikerowehl** [comment]
Looks like you're building under Windows. Sorry, but I don't have any direct experience. I would guess that for some reason it's not picking up the path for the libraries, but I'm not sure what the common crossplatform issues are. On OSX if you run ndk-build with a V=1 argument it'll output the actual commands used to build. Should help a lot of diagnosing the problem.

**Comment by unformatt** [comment]
A temporary hack is to put the lib*.a fles in your android arch-arm\usr\lib\ folder
